name: Code Style

on: push

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Yarn Install
        run: yarn install
      
      - name: Run lint and formatter script
        id: lint-formatter
        run: yarn run lint
