name: Deploy environments

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Yarn install
        run: yarn install

      - name: Build site
        run: yarn run build

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: beta-discordcf-org
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
