name: Deploy environments

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Build
      - run: yarn run build

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=beta-discordcf-org ./dist
